{% set name = "eth-keys" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0abccb83f3d84322591a2c047a1e3aa52ea86b185fa3e82ce311d120ca2791e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-markdown
  run:
    - eth-typing >=3.0.0,<4.0.0
    - eth-utils >=2.0.0,<3.0.0
    - python >=3.7

test:
  imports:
    - eth_keys
    - eth_keys.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-keys
  summary: Common API for Ethereum key operations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
