{% set name = "eth-keys" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5590797f5e2930086c705a6dd1ac14397f74f19bdcd1b5f837475554f354ad8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  build:
    - setuptools
  run:
    - setuptools
    - eth-typing >=2.2.1,<3.0.0
    - eth-utils >=1.8.2,<2.0.0
    - python

test:
  imports:
    - eth_keys
    - eth_keys.backends

about:
  home: https://github.com/ethereum/eth-keys
  summary: Common API for Ethereum key operations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
