{% set name = "eth-keys" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d18887483bc9b8a3fdd8e32ddcb30044b9f08fcb24a380d93b6eee3a5bb3216

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-markdown
  run:
    - eth-typing >=3.0.0,<4.0.0
    - eth-utils >=2.0.0,<3.0.0
    - python >=3.7

test:
  imports:
    - eth_keys
    - eth_keys.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-keys
  summary: Common API for Ethereum key operations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
