{% set name = "eth-keys" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ba33230f851d02c894e83989185b21d76152c49b37e35b61b1d8a6d9f1d20430

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.7
    - setuptools-markdown
  run:
    - eth-utils >=2.0.0
    - eth-typing >=3.0.0
    - python >=3.8

test:
  imports:
    - eth_keys
    - eth_keys.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-keys
  summary: Common API for Ethereum key operations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
